### ISSUE TITLE
Why error404.aspx sets status code to 404 on Render?

### ISSUE THREAD

**Issue by mosessaur** [BlogEngine/BlogEngine.NET#119]
Is there are any particular reason that error404 code behind sets `Response.StatusCode = 404`?
Reason I am asking is that when I setup Application Insights on my blog I started to notice that any requests goes to error404.aspx considered 404 error. So if directly hit error404.aspx page. It get's displayed but reports 404 error on Application Insights! I am suspecting that setting Response.StatusCode to 404 in Render method is the reason.

**Comment by roboffer** [comment]
We use BlogEngine and saw something like this recently, I don't this the problem is that the 404 page is setting the status code - the problem is that you are being redirected to the 404 page rather than staying on the page that was requested. If the URL remains the same, the client is then told that page is a 404 by the status code.

We have out own code repository so handled it there, if you look in UrlRules.cs and change the Response Redirect to a Server Transfer you should get the correct result.

I think we also needed to modify Security.cs to handle a null CurrentUser too as part of this.
