### ISSUE TITLE
What should be the timezone if content writer and reader are from different countries?

### ISSUE THREAD

**Issue by watoo** [BlogEngine/BlogEngine.NET#128]
hi,
The blog writer (Editor) is at UTC +5:00 while blog reader (audience) is at UTC -5:00. So what timezone should I select from admin settings?

**Comment by watoo** [comment]
What is the purpose of timezone settings? Suppose one editor is at UTC + 5:00 and other Editor is at UTC +3:00, then what? I think the better approach would be that while saving a post it should get timezone of browser, and save timezone with each post!

**Comment by rfaix** [comment]
The timezone in Blogengine is useless.

Article are getting shown by using the server time. By writing articles the time from the local device gets used. If you like that your notifications about a new article are getting sent, you have to set the time of the article manually to the server time before publishing it.

If you are using an SQL Server and you try to update the time by a trigger, it even will not help you, because Blogengine even caches the database and in the cache will get used the time from the client. Blogengine is far away from any professional product.

**Comment by kbdavis07** [comment]
Set the time to the time zone of the server that is hosting it.

Do agree through this needs to be improved.
