### ISSUE TITLE
Azure Deployment and Azure AD Authentication support

### ISSUE THREAD

**Issue by acds** [BlogEngine/BlogEngine.NET#169]
Are there plans to even make this more integrated with Azure. Including:
1. Azure AD Authentication (via ADAL ?)
2. User Azure Storage for content files if not using a DB
3. If using a DB for content use Azure SQL
4. Application Insights
4. etc.

**Comment by IrishChieftain** [comment]
I noticed your issue, so started researching this because my plan was to host BE on Azure. I came across a serious memory issue which is a deal breaker if hosting on Azure:

http://timwappat.info/post/2015/08/31/Experiment-moving-BlogEngineNET-to-Azure

This post is from 2015 so I'm wondering if this was addressed?
